# Generated by Django 4.2 on 2023-05-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City_name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_English_name", models.CharField(max_length=255)),
                ("city_Chinese_name", models.CharField(max_length=255)),
            ],
        ),
    ]
