# Generated by Django 4.2.1 on 2023-06-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0006_rename_api_tdx_api"),
    ]

    operations = [
        migrations.CreateModel(
            name="Household_income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("city_name", models.CharField(max_length=255)),
                ("county_code", models.CharField(max_length=255)),
                ("Avg_number_of_househods", models.FloatField()),
                ("Avg_number_of_employment", models.FloatField()),
                ("Avg_number_of_income", models.FloatField()),
                ("Total", models.FloatField()),
            ],
        ),
    ]
