# Generated by Django 4.2.1 on 2023-06-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0009_universities_and_colleges_student_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data_renew_time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("day", models.IntegerField()),
                ("data_name", models.CharField(max_length=255)),
                ("renew_wrong", models.IntegerField()),
            ],
        ),
    ]
