# Generated by Django 4.2.1 on 2023-06-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0010_data_renew_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Year", models.CharField(max_length=255)),
                ("CityName", models.CharField(max_length=255)),
                ("CountyCode", models.CharField(max_length=255)),
                ("Month", models.CharField(max_length=255)),
                ("TownName", models.CharField(max_length=255)),
                ("TownCode", models.CharField(max_length=255)),
                ("NumberOfHousehods", models.IntegerField()),
                ("NumberOfPopulation", models.IntegerField()),
                ("NumberOfMales", models.IntegerField()),
                ("NumberOfFemales", models.IntegerField()),
            ],
        ),
    ]
