# Generated by Django 4.2.1 on 2023-05-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=255)),
                ("county_code", models.CharField(max_length=255)),
                ("month", models.IntegerField()),
                ("vehicle_type", models.CharField(max_length=255)),
                ("value", models.IntegerField()),
            ],
        ),
    ]
