# Generated by Django 4.2.1 on 2023-06-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_city_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="year",
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
