# Generated by Django 4.2.1 on 2023-06-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0007_household_income"),
    ]

    operations = [
        migrations.AlterField(
            model_name="household_income",
            name="year",
            field=models.CharField(max_length=255),
        ),
    ]
