# Generated by Django 4.2.1 on 2023-06-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0011_populationstats"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PopulationStats",
            new_name="Population_stats",
        ),
    ]
